ProjectManagementApp/config/routes.rb
ProjectManagementApp::Application.routes.draw do
  resources :issues
  resources :users,only: [ :new, :create]
  resources :accounts,only: [ :new, :create]
  resources :projects
  root :to => "accounts#new"
  get '/accounts/forgot_password' => 'accounts#forgot_password'
  post '/accounts/get_password' => 'accounts#get_password'
  get "log_out" => "accounts#destroy", :as => "log_out"
  

  

end

ProjectManagementApp/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :require_login
  layout 'account_layout'
  def new
	@user = User.new
  end  
  
  def create    
	user = User.authenticate(params[:login_name], params[:password])
	respond_to do |format|
	  if user
		session[:user_id] = user.id		
		format.html { redirect_to projects_path}
	  else		
		format.html { redirect_to root_url, notice: 'Invalid User Name or Password !'}
	  end
	end
  end
  
  def forgot_password
	@user = User.new	
  end
  
  def get_password
	@user = User.new(user_params)    
	@verify_user = User.find_by_login_name(@user.login_name)
	if (@verify_user.last_name == @user.last_name && @verify_user.email == @user.email) 
		# Generate random password and send mail
		new_password = SecureRandom.hex(8)	
        @verify_user.password = new_password  		
		@verify_user.save!	
		UserMailer.forgot_password(@verify_user ,new_password).deliver
		redirect_to root_url, notice: 'Your new password will be mailed to you'         
    else
        render action: 'forgot_password'        
    end	
  end
  
  def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
  end
  
  def user_params
      params.require(:user).permit(:first_name, :last_name ,:role_id ,:email ,:phone_no , :login_name ,:password )
  end
end

ProjectManagementApp/app/helpers/accounts_helper.rb
module AccountsHelper
end

ProjectManagementApp/app/views/accounts/forgot_password.html.erb
<h1 class="text-info text-center"> Project Management System </h1>
<br/>

<div class="container">

  <fieldset>
	<legend>Forgot Password</legend>
		<%= form_for(@user,:url => accounts_get_password_path ) do |f| %>
		    <div class="form-group">
			<%= f.label :login_name %>
			<%= f.text_field :login_name, :placeholder =>"4 to 20 characters long"%>
			</div> 
		  <div class="form-group">
			<%= f.label :last_name %>
			<%= f.text_field :last_name ,:placeholder =>"last_name" %>
		  </div>
		  <div class="form-group">
			<%= f.label :email %>
			<%= f.text_field :email ,:placeholder =>"Email" %>
		  </div>
		  <div class="actions">
			<%= button_tag(type: "submit", class: "btn btn-primary") do %>
			Get Password 
			<% end %>
		  </div>
		  <% end %>
	</fieldset>

<%= link_to 'Go back to Login Page', new_account_path %>

</div>

ProjectManagementApp/app/views/accounts/new.html.erb
<h1 class="text-info text-center"> Project Management System </h1>
<br/>

<div class="container">
<p id="notice_display"><%= notice %></p>
	<fieldset>
	 <legend class="text-info">Log In</legend>		
		<%= form_tag accounts_path do %>
		  <p>
			<%= label_tag :login_name %>
			<%= text_field_tag :login_name %>
		  </p>
		  <p>
			<%= label_tag :password %>
			<%= password_field_tag :password %>
		  </p>
		  <p><%= button_tag(type: "submit", class: "btn btn-large btn-primary") do %>
				Log In 
			<% end %></p>
		<% end %>
	</fieldset>	


Forgot password? <%= link_to "click here to reset ",accounts_forgot_password_path %> <br/>
New User? <%= link_to "click here to register" , new_user_path %> 

</div>