ProjectManagementApp/config/routes.rb
ProjectManagementApp::Application.routes.draw do
  resources :issues
  resources :users,only: [ :new, :create]
  resources :accounts,only: [ :new, :create]
  resources :projects
  root :to => "accounts#new"
  get '/accounts/forgot_password' => 'accounts#forgot_password'
  post '/accounts/get_password' => 'accounts#get_password'
  get "log_out" => "accounts#destroy", :as => "log_out"
  

  

end

ProjectManagementApp/app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :issue_priority, :class_name => 'Issuepriority', :foreign_key => 'issue_priority_id'
  belongs_to :issue_status, :class_name => 'Issuestatus', :foreign_key => 'issue_status_id'
  belongs_to :project  
  validates_presence_of :issue_priority, :issue_status ,:project
  belongs_to :issue_creator, :class_name => 'User', :foreign_key => 'issue_creator_id'
  belongs_to :issue_assigned, :class_name => 'User', :foreign_key => 'issue_assigned_id'
  
  def self.search(string_search)	
	Issue.where("issue_title LIKE?" ,"%#{string_search}%")		
  end
end

ProjectManagementApp/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  def index 
    if(params.has_key?(:search))
		@string_search = params[:search]  
		@issues = Issue.search(@string_search)
	else
		@issues = Issue.all
	end
	@issues = @issues.paginate(:page => params[:page], :per_page => 4)
  end

  def show	
  end

  def new
    @issue = Issue.new
	@issue.issue_creator_id = current_user.id
  end
  
  def edit    
  end

  def create
    @issue = Issue.new(issue_params)
    
    respond_to do |format|
      if @issue.save
		@user = User.where("id = #{@issue.issue_assigned_id}").first	
		
	    UserMailer.issue_assigned(@user,@issue).deliver
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end
  
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
    end
  end

  private
    def set_issue
      @issue = Issue.find(params[:id])	  
    end

    def issue_params
      params.require(:issue).permit(:project_id, :issue_title, :issue_priority_id, :issue_status_id, :issue_creator_id, :issue_assigned_id, :last_updated_at)
    end

end

ProjectManagementApp/app/helpers/issues_helper.rb
module IssuesHelper
end

ProjectManagementApp/app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id = "error_display">     

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue_title %>
    <%= f.text_field :issue_title %>
  </div>
   <div class="field">
    <%= f.label :project_id %>
    <%= f.select :project_id,Project.all.map { |project| [project.project_name ,project.id] }%>
  </div>
  <div class="field">
    <%= f.label :issue_priority_id %>
    <%= f.select :issue_priority_id,Issuepriority.all.map { |issue| [issue.name , issue.id] } %>
  </div>
  <div class="field">
    <%= f.label :issue_status_id %>
    <%= f.select :issue_status_id,Issuestatus.all.map { |issue| [issue.name , issue.id] } %>
  </div>
  <div class="field">
    <%= f.label :issue_creator_id %>
	<%= current_user.first_name + " " + current_user.last_name %>
	<%= f.text_field :issue_creator_id , :style => "display:none" %>
  </div><br/>
  <div class="field">
    <%= f.label :issue_assigned_id %>
	<%= f.select :issue_assigned_id, options_for_select(User.where("role_id = 3").map { |user| [user.first_name + " " + user.last_name , user.id] })  %>
    
  </div> 
  <div class="field">
	<%= f.label :last_updated_at %>
    <%= f.text_field :last_updated_at, :class => "datepicker" %>
  </div>
  <div class="actions">
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
	 Submit 
	<% end %>
  </div>
<% end %>

ProjectManagementApp/app/views/issues/_list_of_issues.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Issue Title</th>
      <th>Project</th>
      <th>Issue Priority</th>
      <th>Issue Status</th>
      <th>Issue Creator</th>
      <th>Issue Assigned</th>
      <th>Updated at</th> 
      <th> Edit</th>
      <th> Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.issue_title %></td>
        <td><%= issue.project.project_name %></td>
        <td><%= issue.issue_priority.name %></td>
        <td><%= issue.issue_status.name %></td> 
        <td><%= issue.issue_creator.first_name + " " + issue.issue_creator.last_name %></td> 
        <td><%= issue.issue_assigned.first_name + " " + issue.issue_assigned.last_name %></td> 
        <td><%= issue.last_updated_at.to_date %></td> 
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Delete', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @issues, renderer: BootstrapPagination::Rails %>

ProjectManagementApp/app/views/issues/_search.html.erb
<div class="filter_options_container">  
  <form class="filter_form">
    <%= text_field_tag :search, params[:search], :placeholder => "Issue Title" %> 
    <input type="submit" value="search" />
  </form>
</div>

ProjectManagementApp/app/views/issues/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

ProjectManagementApp/app/views/issues/index.html.erb
<h3>Issues List</h3>

<%= link_to 'New Issue', new_issue_path %>
<br/> <br/>

<%= render 'issues/search'%>

<%= render 'issues/list_of_issues' %>
<br>

ProjectManagementApp/app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

ProjectManagementApp/app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<h5> Issue Details</h5>

<p>
  <strong>Issue title:</strong>
  <%= @issue.issue_title %>
</p>

<p>
  <strong>Issue priority Id:</strong>
  <%= @issue.project.project_name %>
</p>

<p>
  <strong>Issue priority Id:</strong>
  <%= @issue.issue_priority.name %>
</p>


<p>
  <strong>Issue status Id:</strong>
  <%= @issue.issue_status.name %>
</p>


<p>
  <strong>Issue assigned Id:</strong>
  <%= @issue.issue_assigned.first_name + " " + @issue.issue_assigned.last_name %>
</p>


<p>
  <strong>Issue Creator Id:</strong>
  <%= @issue.issue_assigned.first_name + " " + @issue.issue_assigned.last_name  %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @issue.last_updated_at.to_date %>
</p>

<br/>
<br/>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>