ProjectManagementApp/config/routes.rb
ProjectManagementApp::Application.routes.draw do
  resources :issues
  resources :users,only: [ :new, :create]
  resources :accounts,only: [ :new, :create]
  resources :projects
  root :to => "accounts#new"
  get '/accounts/forgot_password' => 'accounts#forgot_password'
  post '/accounts/get_password' => 'accounts#get_password'
  get "log_out" => "accounts#destroy", :as => "log_out"
  

  

end

ProjectManagementApp/app/views/layouts/_menu.html.erb
<ul class="nav nav-tabs">
  <li><%= link_to "Project", projects_path %></li>
    <li><%= link_to "Issues", issues_path %></li>    
</ul>

ProjectManagementApp/app/views/layouts/account_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagementApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">      
  
</div>
<%= yield %>

</body>
</html>

ProjectManagementApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectManagementApp</title>   
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %> 
</head>
<body>
   
<div class="container">
<div class="navbar navbar-fixed-top">  
  <div class="navbar-inner">  
    <div class="container"> 
		<h1 class="text-info text-center"> Project Management System </h1>
       <span class="text pull-right">      
		 Logged in as <%= current_user.login_name %> <br/>
		 <%= link_to "Log out", log_out_path %>   
		</span>
    </div>  
  </div>  
</div>
 <br/><br/><br/> <br/><br/><br/>
 <%= render 'layouts/menu' %>  

<%= yield %>
</div>

</body>
</html>